export const userConstants = {
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_FALIURE : "LOGIN_FALIURE",
    LOGOUT : "LOGOUT",



    FETCH_USER_REQUEST : "FETCH_USER_REQUEST",
    FETCH_USER_SUCCESS : "FETCH_USER_SUCCESS",
    FETCH_USER_FALIURE : "FETCH_USER_FALIURE"
}